# generated by datamodel-codegen:
#   filename:  execution_instruction@v3.2.json

from __future__ import annotations
from enum import StrEnum
from typing import Any, Literal
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, confloat
from ulid import ULID


class Transport(StrEnum):
    stdio = "stdio"
    http = "http"


class ToolImplementation(BaseModel):
    """
    [v3.2] Always 'mcp' in v3.1+. Transport details snapshotted from the registry at resolution time.
    """

    protocol: Literal["mcp"]
    transport: Transport
    endpoint: str | None = Field(
        None, description="URL for http transport, command-array digest for stdio"
    )
    image_digest: str | None = Field(
        None, description="Container digest pinning for replay"
    )


class ExecutionMode(StrEnum):
    deterministic = "deterministic"
    probabilistic = "probabilistic"
    hybrid = "hybrid"


class CostBudget(BaseModel):
    class_: str = Field(..., alias="class")
    ceiling_usd: confloat(ge=0.0)


class Decision(StrEnum):
    allow = "allow"
    deny = "deny"
    advisory = "advisory"


class PolicyDecision(BaseModel):
    policy: str
    decision: Decision
    reason: str | None = None
    evaluated_at: AwareDatetime


class Observability(BaseModel):
    trace_id: str
    span_id: str | None = None
    langfuse_session_id: str | None = None


class CallerType(StrEnum):
    n8n = "n8n"
    client_app = "client_app"


class CallerContext(BaseModel):
    """
    [v3.2] Echo of the caller_type and original source for tool-level audit.
    """

    caller_type: CallerType | None = None
    source: str | None = None


class Model(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    contract_id: ULID
    parent_contract_id: ULID | None = Field(
        None,
        description="[v3.2] Causation chain. Null only for the first contract in an intent.",
    )
    intent_id: ULID
    plan_id: ULID
    workflow_id: str | None = None
    workflow_version: str | None = None
    step_id: str
    tool_name: str
    tool_version: str
    tool_implementation: ToolImplementation = Field(
        ...,
        description="[v3.2] Always 'mcp' in v3.1+. Transport details snapshotted from the registry at resolution time.",
    )
    agent_role: str | None = None
    model_class: str | None = None
    execution_mode: ExecutionMode
    input_schema_ref: str
    output_schema_ref: str
    input: dict[str, Any] = Field(
        ..., description="Validated against input_schema_ref before invocation"
    )
    required_capabilities: list[str] | None = None
    declared_side_effects: list[str] | None = None
    cost_budget: CostBudget
    policy_decisions: list[PolicyDecision] = Field(
        ..., description="Snapshot of every policy check that approved this contract."
    )
    observability: Observability
    caller_context: CallerContext | None = Field(
        None,
        description="[v3.2] Echo of the caller_type and original source for tool-level audit.",
    )
    created_at: AwareDatetime | None = None
    signed_by: str | None = None
