# generated by datamodel-codegen:
#   filename:  intent@v3.2.json
#   timestamp: 2026-04-26T19:46:32+00:00

from __future__ import annotations
from enum import StrEnum
from pydantic import AnyUrl, BaseModel, ConfigDict, Field, confloat
from ulid import ULID
from typing import Any


class CallerType(StrEnum):
    """
    [v3.2] Distinguishes the two caller classes for policy and audit.
    """

    n8n = "n8n"
    client_app = "client_app"


class TriggerType(StrEnum):
    webhook = "webhook"
    cron = "cron"
    integration = "integration"
    manual = "manual"
    user_action = "user_action"


class Environment(StrEnum):
    prod = "prod"
    staging = "staging"
    dev = "dev"


class Constraints(BaseModel):
    read_only: bool | None = False
    environment: Environment | None = None
    max_cost_usd: confloat(ge=0.0) | None = None


class Model(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    intent_id: ULID
    source: str = Field(
        ...,
        description="Free-form origin tag, e.g. 'n8n:workflow_42:exec_9876' or 'app:customer_portal:session_abc'",
    )
    caller_type: CallerType = Field(
        ...,
        description="[v3.2] Distinguishes the two caller classes for policy and audit.",
    )
    trigger_type: TriggerType
    requested_outcome: str = Field(
        ...,
        description="Names the workflow contract to resolve, e.g. 'qualify_and_respond'",
    )
    target: str | None = Field(
        None, description="Subject of the intent (lead_id, document_id, etc.)"
    )
    payload: dict[str, Any] = Field(
        ...,
        description="Trigger-specific normalized data. Caller is responsible for normalization.",
    )
    constraints: Constraints
    idempotency_key: str = Field(
        ...,
        description="Required. paperclipai de-dupes on (caller_type, idempotency_key).",
    )
    callback_url: AnyUrl | None = Field(
        None,
        description="[v3.2] Optional. n8n always sets it; client apps may omit and use SSE/polling instead.",
    )
    correlation_id: str | None = None
