# generated by datamodel-codegen:
#   filename:  tool_output@v3.2.json
#   timestamp: 2026-04-26T19:46:36+00:00

from __future__ import annotations
from enum import StrEnum
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, confloat, conint
from typing import Any
from ulid import ULID


class Status(StrEnum):
    success = "success"
    failure = "failure"


class Category(StrEnum):
    """
    [v3.2] Hint for adaptation strategy.
    """

    transient = "transient"
    permanent = "permanent"
    policy = "policy"
    schema = "schema"
    upstream = "upstream"


class Error(BaseModel):
    """
    Required when status=failure. Layered for the Failure Classifier.
    """

    code: str = Field(
        ...,
        description="Structured error code (layer 1 of Failure Classifier). Examples: QUOTA_EXCEEDED, SCHEMA_VIOLATION, UPSTREAM_TIMEOUT, AUTH_FAILED.",
    )
    message: str
    category: Category | None = Field(
        None, description="[v3.2] Hint for adaptation strategy."
    )
    retriable: bool | None = None
    details: dict[str, Any] | None = None


class Metrics(BaseModel):
    """
    [v3.2] Tool-emitted execution metrics. Write-only into observability — never re-enters decisions except through Policy Evaluation.
    """

    duration_ms: conint(ge=0) | None = None
    cost_usd: confloat(ge=0.0) | None = None
    model_used: str | None = Field(
        None, description="Concrete model name. Distinct from contract.model_class."
    )
    model_version: str | None = None
    input_tokens: int | None = None
    output_tokens: int | None = None
    upstream_latency_ms: int | None = None


class Transcript(BaseModel):
    """
    Probabilistic-mode tools must include enough to reconstruct the LLM call.
    """

    messages: list[Any] | None = None
    system_prompt_hash: str | None = None
    stop_reason: str | None = None


class Model(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    contract_id: ULID
    status: Status
    schema_ref: str = Field(
        ..., description="Echoes the contract's output_schema_ref for replay validation"
    )
    data: dict[str, Any] | None = Field(
        None,
        description="Structured output. Required when status=success. Validated against schema_ref.",
    )
    error: Error | None = Field(
        None,
        description="Required when status=failure. Layered for the Failure Classifier.",
    )
    metrics: Metrics | None = Field(
        None,
        description="[v3.2] Tool-emitted execution metrics. Write-only into observability — never re-enters decisions except through Policy Evaluation.",
    )
    side_effects_observed: list[str] | None = Field(
        None,
        description="[v3.2] Side effects the tool actually performed. Must be a subset of contract.declared_side_effects — paperclipai rejects outputs that exceed declarations.",
    )
    transcript: Transcript | None = Field(
        None,
        description="Probabilistic-mode tools must include enough to reconstruct the LLM call.",
    )
    completed_at: AwareDatetime
