# generated by datamodel-codegen:
#   filename:  tool_output@v3.3.json

from __future__ import annotations
from enum import StrEnum
from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    conint,
)
from typing import Any, Literal
from ulid import ULID


class Category(StrEnum):
    """
    Hint for adaptation strategy.
    """

    transient = "transient"
    permanent = "permanent"
    policy = "policy"
    schema = "schema"
    upstream = "upstream"


class ToolError(BaseModel):
    """
    Layered for the Failure Classifier.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    code: str = Field(
        ...,
        description="Structured error code (layer 1 of Failure Classifier). Examples: QUOTA_EXCEEDED, SCHEMA_VIOLATION, UPSTREAM_TIMEOUT, AUTH_FAILED.",
    )
    message: str
    category: Category | None = Field(None, description="Hint for adaptation strategy.")
    retriable: bool | None = None
    details: dict[str, Any] | None = None


class ToolMetrics(BaseModel):
    """
    Tool-emitted execution metrics. Write-only into observability — never re-enters decisions except through Policy Evaluation.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    duration_ms: conint(ge=0) | None = None
    cost_usd: confloat(ge=0.0) | None = None
    model_used: str | None = Field(
        None, description="Concrete model name. Distinct from contract.model_class."
    )
    model_version: str | None = None
    input_tokens: int | None = None
    output_tokens: int | None = None
    upstream_latency_ms: int | None = None


class ToolTranscript(BaseModel):
    """
    Probabilistic-mode tools must include enough to reconstruct the LLM call.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    messages: list[Any] | None = None
    system_prompt_hash: str | None = None
    stop_reason: str | None = None


class ToolOutputSuccess(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    contract_id: ULID
    status: Literal["success"]
    schema_ref: str = Field(
        ..., description="Echoes the contract's output_schema_ref for replay validation"
    )
    data: dict[str, Any] = Field(
        ...,
        description="Structured output. Validated against schema_ref before persistence.",
    )
    metrics: ToolMetrics | None = None
    side_effects_observed: list[str] | None = Field(
        None,
        description="Side effects the tool actually performed. Must be a subset of contract.declared_side_effects.",
    )
    transcript: ToolTranscript | None = None
    completed_at: AwareDatetime


class ToolOutputFailure(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    contract_id: ULID
    status: Literal["failure"]
    schema_ref: str
    error: ToolError
    metrics: ToolMetrics | None = None
    side_effects_observed: list[str] | None = None
    transcript: ToolTranscript | None = None
    completed_at: AwareDatetime


class ToolOutput(RootModel[ToolOutputSuccess | ToolOutputFailure]):
    root: ToolOutputSuccess | ToolOutputFailure = Field(
        ...,
        description="Structured output from any MCP server invocation.",
        discriminator="status",
        title="ToolOutput",
    )
