# generated by datamodel-codegen:
#   filename:  workflow_plan@v3.2.json
#   timestamp: 2026-04-26T20:08:54+00:00

from __future__ import annotations
from enum import StrEnum
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint, constr
from ulid import ULID


class KillSwitch(StrEnum):
    off = "off"
    advisory = "advisory"
    halt = "halt"


class CircuitState(StrEnum):
    closed = "closed"
    half_open = "half_open"
    open = "open"


class PolicySnapshot(BaseModel):
    """
    [v3.2] Frozen result of Policy Evaluation Stage at planning time.
    """

    capabilities_granted: list[str]
    budget_class: str
    budget_remaining_usd: float | None = None
    kill_switch: KillSwitch
    circuit_state: CircuitState


class ExecutionMode(StrEnum):
    deterministic = "deterministic"
    probabilistic = "probabilistic"
    hybrid = "hybrid"


class FallbackStrategy(BaseModel):
    max_retries: conint(ge=0, le=3) | None = None
    fallback_tool: str | None = None
    degrade_to_class: str | None = None


class Step(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    step_id: str
    tool_name: str
    tool_version: str
    model_class: str | None = Field(
        None, description="Required when tool is an LLM MCP server"
    )
    execution_mode: ExecutionMode
    input_schema_ref: str
    output_schema_ref: str
    depends_on: list[str] | None = None
    approval_gate: bool | None = Field(
        False, description="If true, this step emits awaiting_approval before executing"
    )
    fallback_strategy: FallbackStrategy | None = None


class TerminationGuard(BaseModel):
    """
    [v3.2] Plan-scoped limits the Adaptive Engine cannot violate.
    """

    max_chain_depth: int | None = 5
    max_total_cost_usd: float | None = None
    monotone_cost_on_degrade: bool | None = True


class Model(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    plan_id: ULID
    intent_id: ULID
    workflow_id: str = Field(..., description="e.g. 'lead_qualification'")
    workflow_version: constr(pattern=r"^\d+\.\d+\.\d+$")
    agent_role: str | None = Field(
        None,
        description="Which agent role from the registry is responsible for this plan",
    )
    policy_snapshot: PolicySnapshot | None = Field(
        None,
        description="[v3.2] Frozen result of Policy Evaluation Stage at planning time.",
    )
    steps: list[Step] = Field(..., min_length=1)
    termination_guard: TerminationGuard | None = Field(
        None,
        description="[v3.2] Plan-scoped limits the Adaptive Engine cannot violate.",
    )
    created_at: AwareDatetime | None = None
    signed_by: str | None = Field(
        None, description="paperclipai instance + version that produced this plan"
    )
